package exception.exception6;

/**
 * Created by USER on 04.06.2014.
 */
public class SuperSubCatch {
    public static void main(String[] args) {
//        try {
            int a = 0;
            int b = 42/a;
//        } catch (Exception e) {
//            System.out.println("Common Exception");
//        } catch (ArithmeticException e1) {
//            System.out.println("This never has done");
//        }
    }
}
